export enum RouteNames {
	home = 'home',
  	alumnosView = 'alumnosView',
	addAlumnosView = 'addAlumnosView',
	editAlumnosView = 'editAlumnosView',	
	asociacionView = 'asociacionView',
	addAsociacionView = 'addAsociacionView',
	editAsociacionView = 'editAsociacionView',
	clubView = 'clubView',
	addClubView = 'addClubView',
	editClubView = 'editClubView',
	sucursalView = 'sucursalView',
	addSucursalView = 'addSucursalView',
	editSucursalView = 'editSucuralView',
	horariosView = 'horariosView',
	addHorariosView = 'addHorariosView',
	editHorariosView = 'editHorariosView',
	asistenciaView = 'asistenciaView',
	addAsitenciaView = 'adAsitenciaView',
	editAsistenciaView = 'editAsistenciaView',
	asensoView = 'asensoView',
	addAsensoView = 'adAsensoView',
	editAsensoView = 'editAsensoView',
	login = 'login',

	nullRoute = ''
};
